In [22]:
import numpy as np
import pandas as pd

In [9]:
a = np.array([1, 2, 3])
print(a)
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
# ndim to print the dimension 
print(a.ndim)
print(len(a))
listX = [1, 2, 3]
listX[0] = 2
a = a + 5
print(a)
# listX + 5

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1 2 3
1
3
[6 7 8]


In [10]:
data = np.arange(50)
data.shape = (10, 5)
print(data)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [21]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
np.shape(arr)
print(arr.dtype)
print(arr.shape)
print(np.zeros([3,2]))
# print(zeros)

[[1 2 3]
 [4 5 6]]
int64
(2, 3)
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [23]:
d = {"Roll No.": [1,2,3], "Name" : ["Dhruv","Aditya","Deep"], "Marks" : [90, 80, 70]}
df = pd.DataFrame(d)
print(df)   

   Roll No.    Name  Marks
0         1   Dhruv     90
1         2  Aditya     80
2         3    Deep     70


In [24]:
df.head()

Roll No.    Name  Marks
0         1   Dhruv     90
1         2  Aditya     80
2         3    Deep     70

In [33]:
d = {"Roll No.": [1,2,3], "SPI" : [9,10,8], "Marks" : [90, 80, 70]}
df = pd.DataFrame(d, index=['1','2','3'])
print(df)
# print(df.head(1))
# print(df.tail(1))
# df.boxplot(column='Marks', by='SPI')
def addRows(df, row):
    df.loc[len(df)] = row
    return df
df['d'] = df.apply(lambda row: row['SPI'] + row['Marks'], axis=1)
print()
print(df)


   Roll No.  SPI  Marks
1         1    9     90
2         2   10     80
3         3    8     70

   Roll No.  SPI  Marks   d
1         1    9     90  99
2         2   10     80  90
3         3    8     70  78
